#!/bin/bash

# Make sure you have a CHANGELOG.md based on https://keepachangelog.com
# Usage: DEPLOY_TAG="1.0.0" DEPLOY_APP="Your APP" SLACK_HOOK_URL="https://hooks.slack.com/services/AAA/BBB/some_hash" ./jaiminho slack
notify_slack() {
    echo "Notifying slack ..."

    # Cut the CHANGELOG for TAG
    DEPLOY_DESCRIPTION=$(sed -n "/## \[$DEPLOY_TAG\]/,/## \[.*\]/p" CHANGELOG.md | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/\\n/g' | sed -e 's/"/\\"/g')

    # Generate Slack Payload Notification
    cat <<EOF > slack_temp_notification.json
{
  "attachments": [
    {
      "pretext": "*$DEPLOY_APP - Tag: $DEPLOY_TAG*",
      "color": "good",
      "mrkdwn_in": ["fields"],
      "fields": [
        {
          "title": "Changelog",
          "value": "$DEPLOY_DESCRIPTION",
          "short": false
        }
      ]
    }
  ]
}
EOF

    # Notify Slack
    curl -X POST -H 'Content-Type: application/json' -d @slack_temp_notification.json "$SLACK_HOOK_URL"

    # Remove temp files
    rm slack_temp_notification.json
}

# Usage: DEPLOY_TAG="1.0.0" DEPLOY_APP="Your APP" SLACK_CHANGELOG_CHANNEL="#slack-detail-deploy-channel" SLACK_HOOK_URL="https://hooks.slack.com/services/AAA/BBB/some_hash" ./jaiminho slack --short
notify_slack_short() {
    echo "Notifying slack ..."

    # Notify Slack
    curl -X POST --data-urlencode "payload={\"text\": \"Project *$DEPLOY_APP* deployed with tag *$DEPLOY_TAG*. Changelog at *$SLACK_CHANGELOG_CHANNEL*\"}" "$SLACK_HOOK_URL"
}

# Usage: DEPLOY_TAG="1.0.0" NEW_RELIC_APP_ID="some_id" NEW_RELIC_API_KEY="some_api_key" ./jaiminho newrelic
notify_newrelic() {
    echo "Notifying New Relic ..."
    curl -X POST "https://api.newrelic.com/v2/applications/$NEW_RELIC_APP_ID/deployments.json" -H "X-Api-Key:$NEW_RELIC_API_KEY" -i -H 'Content-Type: application/json' -d "{\"deployment\": {\"revision\": \"$DEPLOY_TAG\"}}"
}

version() {
    local version="0.0.3"
    echo "Jaiminho $version"
}

#Starting point
if [ "$1" == "slack" ]; then
   if [ "$2" == "--short" ]; then
       notify_slack_short
       exit 0
   fi
   notify_slack
   exit 0
fi

if [ "$1" == "newrelic" ]; then
    notify_newrelic
    exit 0
fi

if [ "$1" == "--version" ]; then
    version
    exit 0
fi

echo "Usage: ./jaiminho <--version|newrelic|slack>"
exit 1
a
